swagger: '2.0'
info:
  version: 1.0.0
  title: GUSS Account API
host: 'localhost:8080'
basePath: /rest/ugguss/api/v1
schemes:
  - http
paths:
  /profiles/{memberId}:
    get:
      tags:
       - /accounts
      summary: Returns response object for basic member profile info
      description: ''
      operationId: getMember
      produces:
        - application/json
      parameters:
        - name: memberId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/UserProfile'
    post:
      tags:
      - /accounts
      summary: Update User Profile Info
      description: ''
      operationId: updateMember
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            type: object
            items:
              $ref: '#/definitions/UserProfile'
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            items:
              $ref: '#/definitions/UserProfile'
  /registration:
    post:
      description: ''
      operationId: registerUser
      produces:
          - application/json
      parameters:
          - name: userRegistrationRequest
            in: body
            required: true
            schema:
              $ref: '#/definitions/UserRegistrationRequest'
      responses:
          "200":
            description: Succeful Response for user registration
            schema:
                $ref: '#/definitions/UserRegistrationResponse'
  /userType:
    get:
      tags:
        -/userTypes
      summary: Return list of User Types in the application
      description: ''
      operationId: getAllUserTypes
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operations
          schema:
            type: array
            items:
              $ref: '#/definitions/UserType'
  /users/current:
    get:
      tags:
        - /samples
      summary: Returns a simplified JSON representation of Application User object for logged in user (or default user if not logged in)
      description: ''
      operationId: getCurrentUser
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/AppUser'
definitions:
  UserProfile:
    type: object
    properties:
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      middleName:
        type: string
      dob:
        type: string
        format: date
      policyNumber:
        type: integer
        format: int32
  UserType:
    type: object
    properties:
      name:
        $ref: '#/definitions/UserTypeNames'
      description:
        type: string
  Member:
    type: object
    properties:
      userId: 
        type: number
      memberId:
        type: string
      joinDate:
        type: string
      retirementDate:
        type: string
      membershipStatus:
        type: string
        enum:
         - active
         - inactive
      basicSalary:
        type: number
      address:
        type: string
      membershipCategory:
        type: string
        enum:
         - YRA1999
         - YRB2000
  ContributionHistory:
    type: object
    properties:
      documentId:
        type: string
      contributionStartDate:
        type: string
      paymentDate:
        type: string
      fiscalMonthYear:
        type: string
  BaseRequest:
    type: object
    properties:
      userId:
        type: string
      memberId:
        type: string
  BaseResponse:
    type: object
    properties:
      returnCode:
        description: ''
        type: integer
        format: int32
        default: 121
  MemberProfileResponse:
    type: object
    properties:
      baseResponse:
        $ref: '#/definitions/BaseResponse'
      gussMember:
        $ref: '#/definitions/Member'
  UserRegistrationRequest:
    type: object
    properties:
      baseRequest:
        $ref: '#/definitions/BaseRequest'
      member:
        $ref: '#/definitions/Member'
      appUser:
        $ref: '#/definitions/AppUser'
  UserRegistrationResponse:
    type: object
    properties:
      baseResponse:
        $ref: '#/definitions/BaseResponse'
      appUser:
        $ref: '#/definitions/AppUser'
  AppUser:
    type: object
    properties:
      userId: 
        type: number
      dateOfBirth:
        type: string
      email:
        type: string
      password:
        type: string
      firstName:
        type: string
      middleName:
        type: string
      lastName:
        type: string
      dateCreated:
        type: string
      lastUpdatedDate:
        type: string
      userRole:
        $ref: '#/definitions/UserRole'
      status:
        type: number
      gender:
        type: string
        enum:
         - male
         - female
  UserRole:
    type: string
    enum:
    - ADMIN
    - STAFF
    - MEMBER 