swagger: '2.0'
info:
  version: 1.0.0
  title: GUSS Account API
host: 'localhost:8080'
basePath: /guss-app/rest/ugguss/api/v1
schemes:
  - http
paths:
  /profiles/{userName}:
    get:
      tags:
       - user
      summary: Returns response object for basic member profile info
      description: ''
      operationId: getMember
      produces:
        - application/json
      parameters:
        - name: userName
          in: path
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/UserProfileResponse'
    post:
      tags:
      - user
      summary: Update User Profile Info
      description: ''
      operationId: updateMember
      produces:
        - application/json
      parameters:
        - in: body
          name: userProfileRequest
          required: false
          schema:
            type: object
            items:
              $ref: '#/definitions/UserProfile'
        - name: userName
          in: path
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            items:
              $ref: '#/definitions/UserProfile'
  /member-profiles:
    post:
      tags:
      - memberProfile
      summary: Retrieve Member Profile Info
      description: ''
      operationId: retrieveMemberWithMemberId
      produces:
        - application/json
      parameters:
        - in: body
          name: memberProfileRequest
          required: true
          schema:
            $ref: '#/definitions/MemberProfileRequest'
      responses:
        '200':
          description: successful operation
          schema:
              $ref: '#/definitions/UserProfileResponse'
  /registration:
    post:
      tags:
      - registration
      description: ''
      operationId: registerUser
      produces:
          - application/json
      parameters:
          - name: userRegistrationRequest
            in: body
            required: true
            schema:
              $ref: '#/definitions/UserRegistrationRequest'
      responses:
          "200":
            description: Succeful Response for user registration
            schema:
                $ref: '#/definitions/UserRegistrationResponse'
  /token/auth:
     post:
        tags:
        - authentication
        summary: Authenticate User and Generate Token
        description: ''
        operationId: authenticate
        produces:
           - application/json
        parameters: 
           - name: loginRequest
             in: body
             required: true
             schema: 
                $ref: '#/definitions/LoginRequest'
        responses:
           '200':
              description: OK
              schema: 
                 $ref: '#/definitions/AuthToken'
  /userType:
    get:
      tags:
        - user
      summary: Return list of User Types in the application
      description: ''
      operationId: getAllUserTypes
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operations
          schema:
            type: array
            items:
              $ref: '#/definitions/UserType'
  /users/current:
    get:
      tags:
        - user
      summary: Returns a simplified JSON representation of Application User object for logged in user (or default user if not logged in)
      description: ''
      operationId: getCurrentUser
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/AppUser'
  /login:
    get:
      tags:
        - login
      summary: Login User into the portal
      description: ''
      operationId: login
      produces:
        - application/json
      parameters:
        - name: loginRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        '200':
          description: successful operations
          schema:
            $ref: '#/definitions/UserProfile'
  /member-contribution/{memberId}:
    get:
      tags:
        -  memberContribution
      description: 'called to get  all contribution for member'
      operationId: getContribution
      produces:
          - application/json
      parameters:
          - name: memberId
            in: path
            required: true
          - name: startDate
            in: query
            required: false
          - name: endDate
            in: query
            required: false
      responses:
          "200":
            description: Succeful Response for getting guss member contribution history
            schema:
                $ref: '#/definitions/ContributionHistoryResponse'
    put:
      tags:
        -  memberContribution
      description: 'called to create new contribution'
      operationId: createContribution
      produces:
          - application/json
      parameters:
          - name: contributionRequest
            in: body
            required: true
            schema:
              $ref: '#/definitions/ContributionRequest'
          - name: memberId
            in: path
            required: false
      responses:
          "200":
            description: Succeful Response for editing guss member contribution
            schema:
                $ref: '#/definitions/ContributionResponse'
    post:
      tags:
        - memberContribution
      description: 'called to update contribution'
      operationId: updateContribution
      produces:
          - application/json
      parameters:
          - name: contributionRequest
            in: body
            required: true
            schema:
              $ref: '#/definitions/ContributionRequest'
          - name: memberId
            in: path
            required: false
      responses:
          "200":
            description: Succeful Response for editing guss member contribution
            schema:
                $ref: '#/definitions/ContributionResponse'
    delete:
      tags:
        - memberContribution
      description: 'called to delete  member contribution'
      operationId: deleteContribution
      produces:
          - application/json
      parameters:
          - name: memberId
            in: query
            required: true
          - name: contributionRequest
            in: body
            schema:
              $ref: '#/definitions/ContributionRequest'
      responses:
          "200":
            description: Succeful Response for editing guss member contribution
            schema:
                $ref: '#/definitions/ContributionResponse'
definitions:
  UserProfile:
    type: object
    properties:
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      middleName:
        type: string
      dob:
        type: string
        format: date
      policyNumber:
        type: integer
        format: int32
  UserProfileResponse:
    type: object
    properties:
      gussMember:
        $ref: '#/definitions/Member'
      appUser:
        $ref: '#/definitions/AppUser'
      baseResponse:
        $ref: '#/definitions/BaseResponse'
  UserType:
    type: object
    properties:
      name:
        $ref: '#/definitions/UserRole'
      description:
        type: string
  Member:
    type: object
    properties:
      userId: 
        type: number
      memberId:
        type: string
      joinDate:
        type: string
      retirementDate:
        type: string
      membershipStatus:
        type: string
        enum:
         - active
         - inactive
      basicSalary:
        type: number
      address:
        type: string
      membershipCategory:
        $ref: '#/definitions/GussMemberCategory'
      contributionHistory:
        type: array
        items:
          $ref: '#/definitions/Contribution'
  GussMemberCategory:
    type: string
    enum:
    - YRA1999
    - YRB2000
  Contribution:
    type: object
    properties:
      documentId:
        type: string
      paymentDate:
        type: string
      fiscalMonth:
        type: string
      fiscalYear:
        type: string
      amount:
        type: number
      contributionCategory:
        type: string
      dateCreated:
        type: string
      dateUpdated:
        type: string
      comments:
        type: string
      memberId:
        type: string
  BaseRequest:
    type: object
    properties:
      userId:
        type: string
      memberId:
        type: string
  BaseResponse:
    type: object
    properties:
      returnCode:
        description: ''
        type: integer
        format: int32
        default: 121
  MemberProfileResponse:
    type: object
    properties:
      baseResponse:
        $ref: '#/definitions/BaseResponse'
      gussMember:
        $ref: '#/definitions/Member'
  UserRegistrationRequest:
    type: object
    properties:
      baseRequest:
        $ref: '#/definitions/BaseRequest'
      member:
        $ref: '#/definitions/Member'
      appUser:
        $ref: '#/definitions/AppUser'
  UserRegistrationResponse:
    type: object
    properties:
      baseResponse:
        $ref: '#/definitions/BaseResponse'
      appUser:
        $ref: '#/definitions/AppUser'
      gussMember:
        $ref: '#/definitions/Member'
  AppUser:
    type: object
    properties:
      userId: 
        type: number
      dateOfBirth:
        type: string
      email:
        type: string
      password:
        type: string
      firstName:
        type: string
      middleName:
        type: string
      lastName:
        type: string
      dateCreated:
        type: string
      lastUpdatedDate:
        type: string
      userRole:
        $ref: '#/definitions/UserRole'
      status:
        type: number
      gender:
        $ref: '#/definitions/Gender'
  UserRole:
    type: string
    enum:
    - ADMIN
    - STAFF
    - MEMBER
  Gender:
    type: string
    enum:
    - M
    - F
  LoginRequest:
     type: object
     properties:
       email:
          type: string
       password:
          type: string
  AuthToken:
     type: object
     properties:
        token:
           type: string
  ContributionRequest:
    type: object
    properties:
      baseRequest:
        $ref: '#/definitions/BaseRequest'
      contribution:
        $ref: '#/definitions/Contribution'
  ContributionResponse:
    type: object
    properties:
      baseResponse:
        $ref: '#/definitions/BaseResponse'
      contribution:
        $ref: '#/definitions/Contribution'
  ContributionHistoryResponse:
    type: object
    properties:
      baseResponse:
        $ref: '#/definitions/BaseResponse'
      contributionHistory:
        type: array
        items:
          $ref: '#/definitions/Contribution'
  MemberProfileRequest:
    type: object
    properties:
      baseRequest:
        $ref: '#/definitions/BaseRequest'
      memberId:
        type: string