package org.ugguss.model;// default package
// Generated Jun 17, 2018 6:55:19 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * GussMemberContribution generated by hbm2java
 */
@Entity
@Table(name = "guss_member_contribution", catalog = "guss_db", uniqueConstraints = @UniqueConstraint(columnNames = "doc_id"))
public class GussMemberContribution implements java.io.Serializable {

	private int id;
	private GussMember gussMember;
	private String docId;
	private Date paymentDate;
	private Date fiscalMonth;
	private Date fiscalYear;
	private String comments;
	private String contributionCategory;
	private Date dateCreated;
	private Date lastUpdated;
	private BigDecimal amount;

	public GussMemberContribution() {
	}

	public GussMemberContribution(int id, GussMember gussMember, String docId, String contributionCategory) {
		this.id = id;
		this.gussMember = gussMember;
		this.docId = docId;
		this.contributionCategory = contributionCategory;
	}

	public GussMemberContribution(int id, GussMember gussMember, String docId, Date paymentDate, Date fiscalMonth,
			Date fiscalYear, String comments, String contributionCategory, Date dateCreated, Date lastUpdated) {
		this.id = id;
		this.gussMember = gussMember;
		this.docId = docId;
		this.paymentDate = paymentDate;
		this.fiscalMonth = fiscalMonth;
		this.fiscalYear = fiscalYear;
		this.comments = comments;
		this.contributionCategory = contributionCategory;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "guss_member_ssn", nullable = false)
	public GussMember getGussMember() {
		return this.gussMember;
	}

	public void setGussMember(GussMember gussMember) {
		this.gussMember = gussMember;
	}

	@Column(name = "doc_id", unique = true, nullable = false, length = 45)
	public String getDocId() {
		return this.docId;
	}

	public void setDocId(String docId) {
		this.docId = docId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fiscal_month", length = 10)
	public Date getFiscalMonth() {
		return this.fiscalMonth;
	}

	public void setFiscalMonth(Date fiscalMonth) {
		this.fiscalMonth = fiscalMonth;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fiscal_year", length = 10)
	public Date getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(Date fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
	
	@Column(name = "amount")
	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "contribution_category", nullable = false, length = 45)
	public String getContributionCategory() {
		return this.contributionCategory;
	}

	public void setContributionCategory(String contributionCategory) {
		this.contributionCategory = contributionCategory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
