package org.ugguss.model;// default package
// Generated Jun 17, 2018 6:55:19 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * MembershipCategory generated by hbm2java
 */
@Entity
@Table(name = "membership_category", catalog = "guss_db")
public class MembershipCategory implements java.io.Serializable {

	private int id;
	private String categoryName;
	private String description;
	private Set<GussMember> gussMembers = new HashSet<GussMember>(0);

	public MembershipCategory() {
	}

	public MembershipCategory(int id) {
		this.id = id;
	}

	public MembershipCategory(int id, String categoryName, String description, Set<GussMember> gussMembers) {
		this.id = id;
		this.categoryName = categoryName;
		this.description = description;
		this.gussMembers = gussMembers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membershipCategory")
	public Set<GussMember> getGussMembers() {
		return this.gussMembers;
	}

	public void setGussMembers(Set<GussMember> gussMembers) {
		this.gussMembers = gussMembers;
	}

}
