package org.ugguss.model;// default package
// Generated May 30, 2018 7:20:56 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MembershipCategory generated by hbm2java
 */
@Entity
@Table(name = "membership_category", catalog = "guss_db", uniqueConstraints = @UniqueConstraint(columnNames = "category_id"))
public class MembershipCategory implements java.io.Serializable {

	private int id;
	private String categoryId;
	private String categoryName;
	private String description;

	public MembershipCategory() {
	}

	public MembershipCategory(int id) {
		this.id = id;
	}

	public MembershipCategory(int id, String categoryId, String categoryName, String description) {
		this.id = id;
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.description = description;

	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "category_id", unique = true, length = 45)
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}
