package org.ugguss.model;// default package
// Generated Jun 17, 2018 6:55:19 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpringSessionAttributesId generated by hbm2java
 */
@Embeddable
public class SpringSessionAttributesId implements java.io.Serializable {

	private String sessionId;
	private String attributeName;

	public SpringSessionAttributesId() {
	}

	public SpringSessionAttributesId(String sessionId, String attributeName) {
		this.sessionId = sessionId;
		this.attributeName = attributeName;
	}

	@Column(name = "SESSION_ID", nullable = false, length = 36)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "ATTRIBUTE_NAME", nullable = false, length = 200)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpringSessionAttributesId))
			return false;
		SpringSessionAttributesId castOther = (SpringSessionAttributesId) other;

		return ((this.getSessionId() == castOther.getSessionId()) || (this.getSessionId() != null
				&& castOther.getSessionId() != null && this.getSessionId().equals(castOther.getSessionId())))
				&& ((this.getAttributeName() == castOther.getAttributeName())
						|| (this.getAttributeName() != null && castOther.getAttributeName() != null
								&& this.getAttributeName().equals(castOther.getAttributeName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSessionId() == null ? 0 : this.getSessionId().hashCode());
		result = 37 * result + (getAttributeName() == null ? 0 : this.getAttributeName().hashCode());
		return result;
	}

}
