package org.ugguss.model;// default package
// Generated Jun 17, 2018 6:55:19 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpringSession generated by hbm2java
 */
@Entity
@Table(name = "spring_session", catalog = "guss_db")
public class SpringSession implements java.io.Serializable {

	private String sessionId;
	private long creationTime;
	private long lastAccessTime;
	private int maxInactiveInterval;
	private String principalName;
	private Set<SpringSessionAttributes> springSessionAttributeses = new HashSet<SpringSessionAttributes>(0);

	public SpringSession() {
	}

	public SpringSession(String sessionId, long creationTime, long lastAccessTime, int maxInactiveInterval) {
		this.sessionId = sessionId;
		this.creationTime = creationTime;
		this.lastAccessTime = lastAccessTime;
		this.maxInactiveInterval = maxInactiveInterval;
	}

	public SpringSession(String sessionId, long creationTime, long lastAccessTime, int maxInactiveInterval,
			String principalName, Set<SpringSessionAttributes> springSessionAttributeses) {
		this.sessionId = sessionId;
		this.creationTime = creationTime;
		this.lastAccessTime = lastAccessTime;
		this.maxInactiveInterval = maxInactiveInterval;
		this.principalName = principalName;
		this.springSessionAttributeses = springSessionAttributeses;
	}

	@Id

	@Column(name = "SESSION_ID", unique = true, nullable = false, length = 36)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "CREATION_TIME", nullable = false)
	public long getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(long creationTime) {
		this.creationTime = creationTime;
	}

	@Column(name = "LAST_ACCESS_TIME", nullable = false)
	public long getLastAccessTime() {
		return this.lastAccessTime;
	}

	public void setLastAccessTime(long lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

	@Column(name = "MAX_INACTIVE_INTERVAL", nullable = false)
	public int getMaxInactiveInterval() {
		return this.maxInactiveInterval;
	}

	public void setMaxInactiveInterval(int maxInactiveInterval) {
		this.maxInactiveInterval = maxInactiveInterval;
	}

	@Column(name = "PRINCIPAL_NAME", length = 100)
	public String getPrincipalName() {
		return this.principalName;
	}

	public void setPrincipalName(String principalName) {
		this.principalName = principalName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "springSession")
	public Set<SpringSessionAttributes> getSpringSessionAttributeses() {
		return this.springSessionAttributeses;
	}

	public void setSpringSessionAttributeses(Set<SpringSessionAttributes> springSessionAttributeses) {
		this.springSessionAttributeses = springSessionAttributeses;
	}

}
